---
variables:
  DOCKER_REGISTRY_URL: "${NEXUS_DOCKER_DEV_URL}"
  DOCKER_REGISTRY_USER: "${NEXUS_DOCKER_DEV_USER}"
  DOCKER_REGISTRY_PASS: "${NEXUS_DOCKER_DEV_PASS}"

stages:
  - build

build:
  stage: build
  tags:
    - linux
  script:
    - ./build.sh
